### ISSUE TITLE
 **No Action**

### ISSUE THREAD

**Issue by nukeem** [openstore-ecommerce/OS_Reports#1]
Installed the plugin, had an issue as it needed the nbbajax.js to be included. included that but now all i get is:

**No Action**

**Comment by leedavi** [comment]
It's working OK on my dev.  The "No Action" is not generated by OS_Report, that is a generic response, I think when the command does not exists on the system.

I find it odd you had to add some js file?  The "nbbajax.js" is part of the OpenStore install and should ALWAYS be on the install, under NBright\NBrightBuy\Themes\config\js

Is that missing?  If so maybe the install didn't work correctly.

What version of OpenStore are you using and what version of DNN ?

Have you checked the Admnin>plugins ?

Does the "Admin>Reports" tab appear?

Where do you get the "No Action" message?

**Comment by leedavi** [comment]
The "No Action" has also been reported by someone else.  I'll get one of our guys to do a fresh install and see if he can recreate the problem.

**Comment by leedavi** [comment]
In fact, it might be better to get your DNN install.  Can you backup the install and send it to me?

**Comment by nukeem** [comment]
DNN 9.1.1
NB store looks like 3.6.7

I get the Admin > Reports tab, its when i go to that that i get the ** No Action **

Originally when I went to the tab i got a blank page with a js error stating that nbbajax was missing. So i put it into the backend header template.

Unfortunately the client doesn't want me to give you access to the backups. I have just noticed however that when i go to the report page i get Unrecognized Content-Security-Policy directive 'X-Frame-Options:'. in chrome dev tools

**Comment by nukeem** [comment]
ignore this error:  Unrecognized Content-Security-Policy directive 'X-Frame-Options:'. i get it on every page of the site

Also it looks like the OS_reports module does a ajax request to XMLCOnnector with os_reports_getdata command which is what is returning ** No Action **

**Comment by leedavi** [comment]
I can;t think of any reason v3 would not work on DNN9.  But If it doesn't I doubt it will be fixed.

Is this an upgrade of DNN to 9.1.1 ?   OpenStore v4 has been out before DNN9.   So running v3 on DNN9 is OK if it works.  But this looks like the versions will need to be upto date.  Unfortunatly upgrading v3 to v4 is not a simple install, but it is possible, I've done 4 or 5 now.

**Comment by nukeem** [comment]
Found a fix.

For some reason when it installed it didnt set the assembly and namespace details in the plugin settings.

I manually went into the plugin settings and set:
Type: Ajax, 
Assembly: OS_Reports 
Namespace: OpenStore.Providers.OS_Reports.AjaxProvider

Not sure why it didnt go in originally.

**Comment by leedavi** [comment]
OK, good you found an answer.   But it is strange.  I can;t remember the last time we used the reports plugin, but I can't remember a problem.  If there was a problem with the install, maybe something else could be out.  Keep an eye on it.
